ENABLE_LINTERS:
  - PYTHON_BLACK
  - PYTHON_RUFF
  - PYTHON_MYPY
  - PYTHON_BANDIT

FILTER_REGEX_EXCLUDE: >
  (^|/)(\.git|\.venv|venv|node_modules|dist|build|__pycache__)/

APPLY_FIXES: none
FAIL_IF_UPDATED_SOURCES: true
